from __future__ import annotations

from pqc_db.models import (
    Algorithm,
    BlastRadius,
    Certificate,
    CryptoAsset,
    CryptoKnowledge,
    Dependency,
    Edge,
    EvaluationRun,
    Finding,
    FindingEvidence,
    FirewallEvent,
    FirewallPolicy,
    MigrationPlan,
    Node,
    Organization,
    Project,
    Repository,
    Scan,
    SecureDataObject,
    Service,
)


def test_core_models_and_required_tables_are_defined():
    expected = {
        Organization.__tablename__,
        Project.__tablename__,
        Repository.__tablename__,
        Scan.__tablename__,
        Service.__tablename__,
        Certificate.__tablename__,
        CryptoAsset.__tablename__,
        Algorithm.__tablename__,
        Dependency.__tablename__,
        Finding.__tablename__,
        FindingEvidence.__tablename__,
        CryptoKnowledge.__tablename__,
        BlastRadius.__tablename__,
        Node.__tablename__,
        Edge.__tablename__,
        FirewallPolicy.__tablename__,
        FirewallEvent.__tablename__,
        MigrationPlan.__tablename__,
        SecureDataObject.__tablename__,
        EvaluationRun.__tablename__,
    }
    assert expected.issubset({
        "organizations",
        "projects",
        "repositories",
        "scans",
        "services",
        "certificates",
        "crypto_assets",
        "algorithms",
        "dependencies",
        "findings",
        "finding_evidence",
        "crypto_knowledge",
        "blast_radius",
        "nodes",
        "edges",
        "firewall_policies",
        "firewall_events",
        "migration_plans",
        "secure_data_objects",
        "evaluation_runs",
    })
